// user
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//booking
export const FETCH_LIST_TICKET = 'FETCH_LIST_TICKET';

//searching
export const SEARCH_TICKET = 'SEARCH_TICKET';
export const FETCH_START_LIST_PLACE = 'FETCH_START_LIST_PLACE';
export const FETCH_END_LIST_PLACE = 'FETCH_END_LIST_PLACE';
export const FETCH_FILTER_LIST_PLACE = 'FETCH_FILTER_LIST_PLACE';
