// user
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL';

export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const SET_USER_INFO_FAIL = 'SET_USER_INFO_FAIL';

export const CHANGE_PASWORD = 'CHANGE_PASWORD';
export const CHANGE_PASWORD_SUCCESS = 'CHANGE_PASWORD_SUCCESS';
export const CHANGE_PASWORD_FAIL = 'CHANGE_PASWORD_FAIL';

//booking
export const FETCH_LIST_TICKET = 'FETCH_LIST_TICKET';

//searching
export const SEARCH_TICKET = 'SEARCH_TICKET';
export const FETCH_START_LIST_PLACE = 'FETCH_START_LIST_PLACE';
export const FETCH_END_LIST_PLACE = 'FETCH_END_LIST_PLACE';
export const FETCH_FILTER_LIST_PLACE = 'FETCH_FILTER_LIST_PLACE';

