// user
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//booking
export const SEARCH_TICKET_REQUEST = 'SEARCH_TICKET_REQUEST';
export const SEARCH_TICKET_SUCCESS = 'SEARCH_TICKET_SUCCESS';
export const SEARCH_TICKET_FAIL = 'SEARCH_TICKET_FAIL';
